### ISSUE TITLE
Question about trained model

### ISSUE THREAD

**Issue by Shun14** [infrontofme/UWGAN_UIE#5]
Hi, thank you for sharing the project. Can you share the link of trained model?Because of the limit of space of disk, I can't train the model.

**Comment by infrontofme** [comment]
you can download pre-trained models here. 
pretrained model:[[Google Drive](https://drive.google.com/file/d/14SowRxenGwvjkRmGlSfDm8o9iX0m-mEX/view?usp=sharing)]
