### ISSUE TITLE
为什么不能复现UNet的结果？

### ISSUE THREAD

**Issue by DataXujing** [infrontofme/UWGAN_UIE#6]
我使用了作者提供的数据集训练UNet,参数的设定和论文提供的参数设定完全相同，为什么复现不了UNet的修复和去雾结果？生成的图片基本什么也看不到，这是什么原因？求大佬帮助

**Comment by infrontofme** [comment]
您使用提供的数据集利用UWGAN合成fake water images了吗？再用您合成的fake water images和air images组成训练对来训练UNet

**Comment by DataXujing** [comment]
OK,非常感谢

**Comment by DataXujing** [comment]
大佬，在训练UWGAN时需要type1和type2分别训练模型，还是混在一起训练有一个模型就够了？

**Comment by infrontofme** [comment]
需要分不同的水质，分别训练模型

**Comment by DataXujing** [comment]
好的，明白了，非常感谢

**Comment by DataXujing** [comment]
后边的UNet也是分水质训练的对吗？

**Comment by infrontofme** [comment]
分水质训练，也可以尝试几种水质混合在一起训练

**Comment by 18804601171** [comment]
@DataXujing 请问，训练需要做哪些修改嘛

**Comment by DataXujing** [comment]
自己调整一些参数比如，训练的epoch, lr, 优化器及训练数据的路径，就可以训练了

**Comment by shaxiaozi123456** [comment]
你好，请问我用uwgan生成了type1 类型的水下图像，也就是偏绿的图像，然后组成数据集训练u-net，参数设置和文中一样，损失函数用了l1_l2损失，学习率没有用余弦改变那个，就是用的1e-4，处理图像那部分is-aug我没用，只是shuffle了，是不是这部分是关键呀，测试集用的realc，test_one_image那个程序出来的图像感觉就像上了一层蓝，test出来的图像更差，根本就看不见，还有棋盘效应。这个问题出现在哪里呢

**Comment by infrontofme** [comment]
@shaxiaozi123456 这部分不是关键，我们在正常训练中的设置也是采用lr=1e-4，shuffle。realc是公开数据集，里面涵盖的水质和场景比较广，你测试完是所有图像都这样吗？
棋盘效应可能由于损失函数产生，可以参考论文里对loss function分析的部分。

**Comment by infrontofme** [comment]
@shaxiaozi123456 和你说的因素关系应该不大，realc是公开数据集包含的场景复杂，各类水质都有，你是所有测试图像都这样的结果？还是有几张比较差？
我们跑的结果总体还可以，对于一些严重色偏或者雾状效果太重，表现也有待改进。

至于棋盘效应，有可能是损失函数引起的，你可以参考论文中关于loss function分析的部分。

近期，我们会把项目的预训练权重文件和合成的数据集整理后进行开源~

**Comment by shaxiaozi123456** [comment]
我这里所有的图像表现都很差，差到不如不增强，甚至我用训练集的图片用来测试，效果还是差。

**Comment by DataXujing** [comment]
我分水质训练，参数和paper中设置的完全一样，出来的结果也很差。不知道是不是哪里出了问题。

**Comment by shaxiaozi123456** [comment]
> 我分水质训练，参数和paper中设置的完全一样，出来的结果也很差。不知道是不是哪里出了问题。

我也是哎，出来的图片根本看不清

**Comment by infrontofme** [comment]
@shaxiaozi123456 如果用训练集的图片用来测试，效果还很差，那应该是没有训练好，你可以把训练的loss曲线发出来一下，把质量差的图片结果贴上来一下；或者你仔细检查哪个步骤出了问题。

**Comment by shaxiaozi123456** [comment]
![img_real_18](https://user-images.githubusercontent.com/57615671/81878388-75bd0900-95ba-11ea-89ff-dfd2572ad331.png)

**Comment by shaxiaozi123456** [comment]
![img_ori_3](https://user-images.githubusercontent.com/57615671/81878507-db10fa00-95ba-11ea-8b2c-50383e3302d7.png)
![img_ori_18](https://user-images.githubusercontent.com/57615671/81878509-dcdabd80-95ba-11ea-8cac-1af2c21b87d2.png)
![img_real_18](https://user-images.githubusercontent.com/57615671/81878510-dd735400-95ba-11ea-94d7-5d5198313d85.png)
![res_gen100_18](https://user-images.githubusercontent.com/57615671/81878512-de0bea80-95ba-11ea-9bdb-cd4696b3ac1c.png)
![res_gen200_3](https://user-images.githubusercontent.com/57615671/81878513-df3d1780-95ba-11ea-8878-f95c5ae028e7.png)

**Comment by shaxiaozi123456** [comment]
在test_one_image中测试的realc的数据和训练集的数据，realc的数据都是这种偏蓝色，训练集数据恢复的也不太好

**Comment by infrontofme** [comment]
in-air images: 
![air_000000_000](https://user-images.githubusercontent.com/34626896/81879823-5c1dc080-95be-11ea-9b8a-8d6cff458f34.png)
syn-fake images:
3 types
![fake_000000_000](https://user-images.githubusercontent.com/34626896/81879871-7ce61600-95be-11ea-94fb-b7243d2b7702.png) ![fake_000000_000](https://user-images.githubusercontent.com/34626896/81879903-8ff8e600-95be-11ea-92e9-963defda5c28.png) ![fake_000000_000](https://user-images.githubusercontent.com/34626896/81879891-87081480-95be-11ea-8f6f-10eb63d18390.png)

restored in-air images: l1+msssim loss
![fake_000000_000_gen](https://user-images.githubusercontent.com/34626896/81880000-d0586400-95be-11ea-9164-89dfaee004cb.png)

water images:
![18_img_](https://user-images.githubusercontent.com/34626896/81880028-ed8d3280-95be-11ea-9480-804572345815.png)
![73_img_](https://user-images.githubusercontent.com/34626896/81880592-6d67cc80-95c0-11ea-9de8-3d012497ff9b.png)
![87_img_](https://user-images.githubusercontent.com/34626896/81880626-7fe20600-95c0-11ea-864c-8f8697bec08a.png)
![380_img_](https://user-images.githubusercontent.com/34626896/81880729-c20b4780-95c0-11ea-858e-b1014e0942fc.png)
![515_img_](https://user-images.githubusercontent.com/34626896/81880932-5a093100-95c1-11ea-92c6-d22f957a597a.png)
![635_img_](https://user-images.githubusercontent.com/34626896/81881064-ca17b700-95c1-11ea-8331-733172ef91eb.png)


restored water images:
![18_img__gen](https://user-images.githubusercontent.com/34626896/81880415-0cd88f80-95c0-11ea-8dcc-64c7953927dd.png)
![73_img__gen](https://user-images.githubusercontent.com/34626896/81880633-86707d80-95c0-11ea-976e-ea44ae7eaa01.png)
![87_img__gen](https://user-images.githubusercontent.com/34626896/81880659-94be9980-95c0-11ea-9802-e142e460014a.png)
![380_img__gen](https://user-images.githubusercontent.com/34626896/81880746-cafc1900-95c0-11ea-881b-bc193e840d5c.png)
![515_img__gen](https://user-images.githubusercontent.com/34626896/81880934-5d9cb800-95c1-11ea-8a55-965e75ecb63c.png)
![635_img__gen](https://user-images.githubusercontent.com/34626896/81881076-d13ec500-95c1-11ea-9190-9e4f6f8fcca0.png)

realc包含的水下场景很丰富，这种方法并不是在所有的场景下都能work，这也是水下图像增强算法的挑战。基于deep-learning的方法依赖训练集的质量，在模式比较接近的场景能够起到较好的效果。我们也正在做一些改进的工作，想要兼顾实时和较好的效果，拟融合一些先验知识到深度学习网络里，欢迎交流！

**Comment by shaxiaozi123456** [comment]
假如我全用绿的那种type，那么测试集偏绿的效果自然会好一些，如果混合三种type，是不是需要选择性的将某些空中图片对应水下图片，比如说空中图片相近的几张都类似，所以把这几张类似的图片分别对应不同type的水下图片，这样训练的模型泛华性能是不是应该好些，你们是怎么选择的，你们的实验的确做的很棒，就是我复现一个相对好的结果有点困难

**Comment by infrontofme** [comment]
使用UWGAN合成的水下数据集已上传到Google Drive，

> fake water images generated from UWGAN: [[Google Drive](https://drive.google.com/open?id=1Vy1HtFYY9U7QlMa0Qo8EGCTBuR3_QWb-)]

**Comment by shaxiaozi123456** [comment]
能上传到百度云吗
