### ISSUE TITLE
你好，请问可以把type1和type2混合在一起进行训练嘛？另外，训练gan时参数应该如何设置呢？

### ISSUE THREAD

**Issue by 18804601171** [infrontofme/UWGAN_UIE#7]

**Comment by infrontofme** [comment]
训练GAN网络时建议分开，可以生成多种水质的fake water images。
与图像光衰减和雾状效果的参数调整可以参考https://github.com/infrontofme/UWGAN_UIE/issues/3#issuecomment-571580930 这个回答。其他参数可以参照uwgan_main.py，batch_size大小根据显卡内存自己调整。

**Comment by 18804601171** [comment]
我在训练时，报错，说找不到UWGAN这个模块，但是明明导入了
